### ISSUE TITLE
ESP32 S2 missing include

### ISSUE THREAD

**Issue by besanur** [theelims/ESP32-sveltekit#23]
Hello,

I have updated my project to the latest version.

I had to adjust one thing in **SystemStatus.cpp**. 

There is a missing include after the condition:
```
#elif CONFIG_IDF_TARGET_ESP32S2 
#include "esp32/rom/rtc.h"
```
otherwise I get errors with  `root["cpu_reset_reason"] = verbosePrintResetReason(rtc_get_reset_reason(0));`

**Comment by theelims** [comment]
I haven't tested the code on the S2. Thanks for pointing these changes out. I'll get a S2 board and include that in my future tests.
