### ISSUE TITLE
postcss.config.cjs as ESM module

### ISSUE THREAD

**Issue by thiccnfun** [theelims/ESP32-sveltekit#24]
This isn't so much an issue, but something I wanted to share here.

[Longer story short](https://github.com/saadeghi/daisyui/discussions/2083), I was having a hard time getting the `postcss-remove-class` plugin to work with the way `postcss.config.cjs` was defined.

This ESM approach worked better for me (renamed as `postcss.config.js`):

```js filename="postcss.config.js"
import tailwindcss from 'tailwindcss';
import autoprefixer from 'autoprefixer';
import postcssRemoveClasses from 'postcss-remove-classes';

export default {
  plugins: [
    tailwindcss(),
    autoprefixer(),
    postcssRemoveClasses.default('range'),
  ],
}
```

There may be a solution using the previous format of the file, but I wasn't finding the approach very intuitive 🤷

**Comment by theelims** [comment]
Made this the standard way for next release
