### ISSUE TITLE
WebSerial Monitor. Not an Issue, only a contribution of a github newbie

### ISSUE THREAD

**Issue by SolarDaniel** [theelims/ESP32-sveltekit#28]
Sorry, I'm only a retired hobbyist and not (yet) familiar with github and don't know how to fork and contribute with pull requests.
But maybe someone is interested in what I did and maybe it would be a nice extension to features.

[WebSerial.zip](https://github.com/theelims/ESP32-sveltekit/files/14814546/WebSerial.zip)

WebSerialClass inherits from Arduino Print and can be used like Serial.print() and all other print functions.
It opens a WebSocketClient and sends to clients instead to HwSerial.

On the UI side there's a <textarea> element that acts like a Serial Monitor in platformio, where all content received over the WebSocket is printed. Includes toggling Start/Stop button and Clear button.

How to use:
In main.cpp
```
WebSerialClass WebSerial = WebSerialClass(&server);

void setup()
{
    // start serial and filesystem
    Serial.begin(SERIAL_BAUD_RATE);

    // start ESP32-SvelteKit
    esp32sveltekit.begin();
    WebSerial.begin();
}
```
Anywhere else
```
WebSerial.println("7EA08BCEFF31....3EDBB88FC0D5333092E61348397E");
```

I hope someone likes it. For me it is very helpfull, cause all my serial ports are used.
Probably it needs some professional improvement.

![Monitor GUI](https://github.com/theelims/ESP32-sveltekit/assets/38322666/badfd493-e52a-4fde-ba36-74ee9ee12de2)

**Comment by theelims** [comment]
@SolarDaniel Thank you for that contribution. I'll not include this into the main branch, but I'll leave it here for others to draw inspiration from.

However, I've thought about this as well, but would need to pipe all serial info to a websocket, including the ESP_LOG debug statements. Maybe I'll come back to this at a later time.
