### ISSUE TITLE
ESP32-sveltekit is crashing with latest platform 6.4.0

### ISSUE THREAD

**Issue by EvEggelen** [theelims/ESP32-sveltekit#5]
Problem. Code builds with both 6.4.0 ( platform = espressif32@6.4.0 )and 6.3.2 ( platform = espressif32@6.3.2 ). But crashes during startup when platform 6.4.0 is used. 

*ESP32-sveltekit:**
https://github.com/theelims/ESP32-sveltekit/releases/tag/v0.2.0

**Added to platformio.ini**
[env:nodemcu-32s]
board = nodemcu-32s
board_build.partitions = min_spiffs.csv

**Hardware:**
https://www.aliexpress.com/item/1005001636295529.html

**Log when using 6.4.0**
esptool.py v4.5.1
Creating esp32 image...
Merged 25 ELF sections
Successfully created esp32 image.
Configuring upload protocol...
AVAILABLE: cmsis-dap, esp-bridge, esp-prog, espota, esptool, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa
CURRENT: upload_protocol = esptool
Looking for upload port...
Auto-detected: /dev/ttyUSB0
Uploading .pio/build/nodemcu-32s/firmware.bin
esptool.py v4.5.1
Serial port /dev/ttyUSB0
Connecting....
Chip is ESP32-D0WD-V3 (revision v3.1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: b0:a7:32:28:a6:20
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Flash will be erased from 0x00001000 to 0x00005fff...
Flash will be erased from 0x00008000 to 0x00008fff...
Flash will be erased from 0x0000e000 to 0x0000ffff...
Flash will be erased from 0x00010000 to 0x00164fff...
Compressed 17536 bytes to 12203...
Writing at 0x00001000... (100 %)
Wrote 17536 bytes (12203 compressed) at 0x00001000 in 0.4 seconds (effective 358.0 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 146...
Writing at 0x00008000... (100 %)
Wrote 3072 bytes (146 compressed) at 0x00008000 in 0.0 seconds (effective 1073.2 kbit/s)...
Hash of data verified.
Compressed 8192 bytes to 47...
Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.0 seconds (effective 1635.5 kbit/s)...
Hash of data verified.
Compressed 1394048 bytes to 925247...
Writing at 0x00010000... (1 %)
Writing at 0x00014c6e... (3 %)
Writing at 0x00018c8f... (5 %)
Writing at 0x0001cd63... (7 %)
Writing at 0x00020d5d... (8 %)
Writing at 0x00024d60... (10 %)
Writing at 0x00028d58... (12 %)
Writing at 0x0002cd53... (14 %)
Writing at 0x00030d4e... (15 %)
Writing at 0x00035ea0... (17 %)
Writing at 0x00039e87... (19 %)
Writing at 0x00044150... (21 %)
Writing at 0x0004fd11... (22 %)
Writing at 0x0005b3fe... (24 %)
Writing at 0x0006686a... (26 %)
Writing at 0x00077ce5... (28 %)
Writing at 0x0007d291... (29 %)
Writing at 0x00082e24... (31 %)
Writing at 0x00089a76... (33 %)
Writing at 0x0008fe75... (35 %)
Writing at 0x00096990... (36 %)
Writing at 0x0009dd58... (38 %)
Writing at 0x000a3adf... (40 %)
Writing at 0x000a92f4... (42 %)
Writing at 0x000aed52... (43 %)
Writing at 0x000b407b... (45 %)
Writing at 0x000b93c1... (47 %)
Writing at 0x000be65c... (49 %)
Writing at 0x000c3d00... (50 %)
Writing at 0x000c9064... (52 %)
Writing at 0x000ce27e... (54 %)
Writing at 0x000d37ed... (56 %)
Writing at 0x000d88ea... (57 %)
Writing at 0x000ddd28... (59 %)
Writing at 0x000e2d29... (61 %)
Writing at 0x000e82aa... (63 %)
Writing at 0x000ede72... (64 %)
Writing at 0x000f3511... (66 %)
Writing at 0x000f8986... (68 %)
Writing at 0x000fdb4d... (70 %)
Writing at 0x00103002... (71 %)
Writing at 0x001081e6... (73 %)
Writing at 0x0010d90e... (75 %)
Writing at 0x0011302f... (77 %)
Writing at 0x00118c50... (78 %)
Writing at 0x0011e788... (80 %)
Writing at 0x001241c5... (82 %)
Writing at 0x00129d9f... (84 %)
Writing at 0x0012f5eb... (85 %)
Writing at 0x00134708... (87 %)
Writing at 0x0013a3fe... (89 %)
Writing at 0x00142b2e... (91 %)
Writing at 0x0014b998... (92 %)
Writing at 0x0015181f... (94 %)
Writing at 0x00156cb3... (96 %)
Writing at 0x0015c1eb... (98 %)
Writing at 0x00161a28... (100 %)
Wrote 1394048 bytes (925247 compressed) at 0x00010000 in 20.7 seconds (effective 538.1 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

Please build project in debug configuration to get more details about an exception.
See https://docs.platformio.org/page/projectconf/build_configurations.html

--- Terminal on /dev/ttyUSB0 | 115200 8-N-1
--- Available filters and text transformations: colorize, debug, default, direct, esp32_exception_decoder, hexlify, log2file, nocontrol, printable, send_on_enter, time
--- More details at https://bit.ly/pio-monitor-filters
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H
ets Jul 29 2019 12:21:46

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4
ets Jul 29 2019 12:21:46

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4
ets Jul 29 2019 12:21:46

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4

**Log when using 6.3.2**

Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  16.2% (used 53036 bytes from 327680 bytes)
Flash: [=======   ]  70.5% (used 1385797 bytes from 1966080 bytes)
Building .pio/build/nodemcu-32s/firmware.bin
esptool.py v4.5.1
Creating esp32 image...
Merged 25 ELF sections
Successfully created esp32 image.
Configuring upload protocol...
AVAILABLE: cmsis-dap, esp-bridge, esp-prog, espota, esptool, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa
CURRENT: upload_protocol = esptool
Looking for upload port...
Auto-detected: /dev/ttyUSB0
Uploading .pio/build/nodemcu-32s/firmware.bin
esptool.py v4.5.1
Serial port /dev/ttyUSB0
Connecting....
Chip is ESP32-D0WD-V3 (revision v3.1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: b0:a7:32:28:a6:20
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Flash will be erased from 0x00001000 to 0x00005fff...
Flash will be erased from 0x00008000 to 0x00008fff...
Flash will be erased from 0x0000e000 to 0x0000ffff...
Flash will be erased from 0x00010000 to 0x00163fff...
Compressed 17488 bytes to 12168...
Writing at 0x00001000... (100 %)
Wrote 17488 bytes (12168 compressed) at 0x00001000 in 0.4 seconds (effective 356.2 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 146...
Writing at 0x00008000... (100 %)
Wrote 3072 bytes (146 compressed) at 0x00008000 in 0.0 seconds (effective 1064.7 kbit/s)...
Hash of data verified.
Compressed 8192 bytes to 47...
Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.0 seconds (effective 1614.9 kbit/s)...
Hash of data verified.
Compressed 1391680 bytes to 924200...
Writing at 0x00010000... (1 %)
Writing at 0x000157ab... (3 %)
Writing at 0x000197cb... (5 %)
Writing at 0x0001d899... (7 %)
Writing at 0x0002189d... (8 %)
Writing at 0x0002589a... (10 %)
Writing at 0x0002989e... (12 %)
Writing at 0x0002d899... (14 %)
Writing at 0x00031894... (15 %)
Writing at 0x000369e3... (17 %)
Writing at 0x0003a9cb... (19 %)
Writing at 0x00043d0e... (21 %)
Writing at 0x0004fcdd... (22 %)
Writing at 0x0005b2ac... (24 %)
Writing at 0x000667d9... (26 %)
Writing at 0x00077b09... (28 %)
Writing at 0x0007d07c... (29 %)
Writing at 0x00082c4d... (31 %)
Writing at 0x000898a5... (33 %)
Writing at 0x0008fc6a... (35 %)
Writing at 0x0009677d... (36 %)
Writing at 0x0009dae0... (38 %)
Writing at 0x000a383e... (40 %)
Writing at 0x000a90a8... (42 %)
Writing at 0x000aeaee... (43 %)
Writing at 0x000b3e02... (45 %)
Writing at 0x000b9163... (47 %)
Writing at 0x000be403... (49 %)
Writing at 0x000c3aa8... (50 %)
Writing at 0x000c8e71... (52 %)
Writing at 0x000cdf9f... (54 %)
Writing at 0x000d34a2... (56 %)
Writing at 0x000d854b... (57 %)
Writing at 0x000dd95b... (59 %)
Writing at 0x000e2985... (61 %)
Writing at 0x000e7f0c... (63 %)
Writing at 0x000eda5e... (64 %)
Writing at 0x000f310a... (66 %)
Writing at 0x000f8618... (68 %)
Writing at 0x000fd77e... (70 %)
Writing at 0x00102c10... (71 %)
Writing at 0x00107daa... (73 %)
Writing at 0x0010d4b5... (75 %)
Writing at 0x00112bf9... (77 %)
Writing at 0x001188e0... (78 %)
Writing at 0x0011e470... (80 %)
Writing at 0x00123db8... (82 %)
Writing at 0x001299be... (84 %)
Writing at 0x0012f116... (85 %)
Writing at 0x00134280... (87 %)
Writing at 0x0013a03f... (89 %)
Writing at 0x0014263f... (91 %)
Writing at 0x0014bb72... (92 %)
Writing at 0x0015131a... (94 %)
Writing at 0x001569ec... (96 %)
Writing at 0x0015bd4a... (98 %)
Writing at 0x001616b4... (100 %)
Wrote 1391680 bytes (924200 compressed) at 0x00010000 in 20.7 seconds (effective 537.4 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

Please build project in debug configuration to get more details about an exception.
See https://docs.platformio.org/page/projectconf/build_configurations.html

--- Terminal on /dev/ttyUSB0 | 115200 8-N-1
--- Available filters and text transformations: colorize, debug, default, direct, esp32_exception_decoder, hexlify, log2file, nocontrol, printable, send_on_enter, time
--- More details at https://bit.ly/pio-monitor-filters
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H
[     8][E][WiFiGeneric.cpp:680] wifiLowLevelInit(): esp_wifi_init 4353
[    45][D][esp32-hal-cpu.c:244] setCpuFrequencyMhz(): PLL: 480 / 2 = 240 Mhz, APB: 80000000 Hz
Running Firmware Version: 0.2.0
Starting software access point
[   288][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 0 - WIFI_READY
[   394][V][WiFiGeneric.cpp:392] _arduino_event_cb(): AP Started
[   395][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 10 - AP_START
[   399][V][WiFiGeneric.cpp:97] set_esp_interface_ip(): Configuring SoftAP static IP: 192.168.4.1, MASK: 255.255.255.0, GW: 192.168.4.1
[   408][V][WiFiGeneric.cpp:143] set_esp_interface_ip(): SoftAP: 192.168.4.1 | Gateway: 192.168.4.1 | DHCP Start: 0.0.0.0 | Netmask: 255.255.255.0
[   421][V][WiFiGeneric.cpp:190] set_esp_interface_ip(): DHCP Server Range: 192.168.4.2 to 192.168.4.12
[   987][V][WiFiGeneric.cpp:395] _arduino_event_cb(): AP Stopped
[   988][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 11 - AP_STOP
[   988][V][WiFiGeneric.cpp:392] _arduino_event_cb(): AP Started
[   995][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 10 - AP_START
Starting captive portal on 192.168.4.1

**Comment by theelims** [comment]
Hi,

I've observed this behavior as well. That's why I pushed a small update 4 days ago, if you use the latest version. For now the only way around that is to stick with:
```platform = espressif32 @ 6.3.2```

It lock's up during start-up as one thread consumes all CPU power to the point, that not even the IDLE-Task is served anymore. But I have no clue what could cause this.

**Comment by theelims** [comment]
It looks like esp8266-react from which it forks is affected as well. There is an issue open at https://github.com/rjwats/esp8266-react/issues/329 

I'll have a look at the solution and give it a try.

**Comment by theelims** [comment]
Released v0.2.1 with the fixes from the open esp8266-react PR.
