### ISSUE TITLE
Getting Started: WebSocket Not Working

### ISSUE THREAD

**Issue by IanSC** [theelims/ESP32-sveltekit#54]
I had some trouble but got it to run, so I am just verifying if the solution is correct,
and it might help others too.

When this repo is run, I get message on the browser "Connection to device lost".
Toggling the light using REST is working.
Socket is not working.

I tried this solution and it solves the web socket issue:
https://stackoverflow.com/questions/69350342/svelte-sveltekit-and-socket-io-client-not-working-in-dev-works-in-preview

It says to add to `svelte.config.js`
```
const config = {
  kit: {
    vite: {
      resolve: {
        alias: {
          "xmlhttprequest-ssl": "./node_modules/engine.io-client/lib/xmlhttprequest.js",
        },
      },
    },
  },
};
```
Is this the recommended solution?

Thank you for the great lib.

**Comment by theelims** [comment]
Can you please elaborate your setup a little bit? Which browser, are you using the vite proxy, which versions, ...

There are known issues with opera and edge #52
