### ISSUE TITLE
web interface

### ISSUE THREAD

**Issue by JonyBest** [theelims/ESP32-sveltekit#56]
Help, I can't figure out how to transfer the sensor value to the web interface. You can use a detailed example with an explanation.

**Comment by theelims** [comment]
@JonyBest It is described in the docs how to update a state and push a new value to the web interface:
https://theelims.github.io/ESP32-sveltekit/statefulservice/#read-update-state

You could define your sensor class
```cpp
class SensorState {
 public:
  uint32_t sensorValue = 255;

// remaining code like in the lightstate example
};
```
and update it in your Arduino loop()-function
```cpp
void loop()
{
  uint32_t readSensor = sensor.read();
  sensorStateService.update([&](SensorState& state) {
    state.sensorValue = readSensor;  
    return StateUpdateResult::CHANGED; 
  }, "loop");

  delay(100);
}
```
