### ISSUE TITLE
Parsing the GET request parameters

### ISSUE THREAD

**Issue by thedemoncat** [theelims/ESP32-sveltekit#66]
Good afternoon!

I couldn't figure out how to process the request parameters in the GET method. 
Can you give examples, yes, an example of a demo function?

**Comment by theelims** [comment]
Hi, ESP32-sveltekit does not use these for communication. Please refer to the PsychicHTTP GitHub for this question.

**Comment by thedemoncat** [comment]
So I got it right. Thanks for the answer
